#! /bin/bash

export PATH=~/.bin:/opt/desktop/bin:/unified-setup/opt/desktop/bin:$PATH:/snap/bin;

# lightdm will not have a wallpaper spread across screens
wm-switch-wallpaper;

[ -r /opt/desktop/xsession-extra ] && source /opt/desktop/xsession-extra;

# Load X resources file
if [ -z "$LIGHT_MODE" ]
then
    xrdb /unified-setup/home/.Xdefaults &
else
    xrdb /unified-setup/home/.Xdefaults.light &
fi

exec i3;
