#! /bin/bash

#setup screens
xrandr --output DP2 --auto --pos 0x0 --output DP1 --auto --pos 2560x400
# setup touch screen
touch_input=$(xinput | grep CoolTouchR | sed -E "s/.*CoolTouchR System\s+id=([0-9]+).*/\1/")
xinput --map-to-output $touch_input DP2
# pick wallpaper for lightdm-gtk
/unified-setup/opt/desktop/pick-random-wallpaper
