#! /bin/bash

export PATH=~/.bin:/unified-setup/opt/desktop/bin:$PATH;

# lightdm will not have a wallpaper spread across screens
wm-switch-wallpaper;

[ -r /opt/desktop/xsession-extra ] && source /opt/desktop/xsession-extra;

xcompmgr &

(sleep 1s && python3 /unified-setup/opt/desktop/i3-plugin.py) &

(node /unified-setup/opt/desktop/status.js) &

i3;
