#!/bin/bash

build_user=sam
build_dir=/tmp/aurget

mkdir $build_dir
chown $build_user $build_dir

cp /unified-setup/aur/aurget-PKGBUILD ${build_dir}/PKGBUILD
su - $build_user -c "cd ${build_dir}; git clone /unified-setup/external/aurget ./src; makepkg"

cp /tmp/aurget/aurget-4.7.2-1-any.pkg.tar.zst /var/cache/pacman/pkg/
pacman -U /var/cache/pacman/pkg/aurget-4.7.2-1-any.pkg.tar.zst
