#!/bin/bash

# install dependency python-notify2
/unified-setup/aur/python-notify2-install

build_user=sam
build_dir=/tmp/aurget

rm -rf $build_dir
mkdir $build_dir
chown $build_user $build_dir

cp /unified-setup/aur/openrazer-daemon.install ${build_dir}/
cp /unified-setup/aur/openrazer-driver-dkms.install ${build_dir}/
cp /unified-setup/aur/openrazer-meta-PKGBUILD ${build_dir}/PKGBUILD
su - $build_user -c "cd ${build_dir}; makepkg"

cp /tmp/aurget/openrazer-daemon-2.5.0-1-any.pkg.tar.xz \
   /tmp/aurget/openrazer-driver-dkms-2.5.0-1-any.pkg.tar.xz \
   /tmp/aurget/openrazer-meta-2.5.0-1-any.pkg.tar.xz \
   /tmp/aurget/python-openrazer-2.5.0-1-any.pkg.tar.xz \
   /var/cache/pacman/pkg/
pacman -U \
       /var/cache/pacman/pkg/openrazer-daemon-2.5.0-1-any.pkg.tar.xz \
       /var/cache/pacman/pkg/openrazer-driver-dkms-2.5.0-1-any.pkg.tar.xz \
       /var/cache/pacman/pkg/openrazer-meta-2.5.0-1-any.pkg.tar.xz \
       /var/cache/pacman/pkg/python-openrazer-2.5.0-1-any.pkg.tar.xz

# add sam to group that allows controlling keyboard lights
gpasswd -a sam plugdev
